### ISSUE TITLE
PRACTICA DE COMPUERTAS LÓGICAS

### ISSUE THREAD

**Issue by Edwin14459** [SistemasTecTlaxiaco/compuertas-logicas-equipo-de-uriel-edwin-araceli-1as#2]
[PRACTICA DE COMPUERTAS LÓGICAS.pdf](https://github.com/SistemasTecTlaxiaco/compuertas-logicas-equipo-de-uriel-edwin-araceli-1as/files/7732103/PRACTICA.DE.COMPUERTAS.LOGICAS.pdf)

**Comment by yaritzaov123** [comment]
Portada:25
Procedimiento:22, la tabla de verdad del punto número 3 está mal porque la expresion de su tabla de verdad no coincide con la expresión original y el mapa de Karnaugh no coincide con su tabla de verdad que diseñaron 
Figuras :25
Resultados y conclusiones: 25
calificacion: 29/30

**Comment by josealfredo79** [comment]
Bien hecho y revisado
